services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    env_file:
      - ${CONFIG_BASE_PATH}/service/keycloak/secret/admin.env
      - ${CONFIG_BASE_PATH}/service/keycloak/keycloak.env
    ports:
      - "0.0.0.0:8224:8080"
      - "127.0.0.1:9228:9000"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 10s
      timeout: 10s
      start_period: 15s
      retries: 5
    command:
      - "start-dev"
      - "--import-realm"
      - "--spi-connections-http-client-default-connection-ttl-millis=300000"
      - "--metrics-enabled=true"
    volumes:
      - ${CONFIG_BASE_PATH}/service/keycloak/realm:/opt/keycloak/data/import
    networks:
      - service_keycloak_network
      - service_postgres_network

volumes:
  postgres_data:

networks:
  service_keycloak_network:
    external: true
  service_postgres_network:
    external: true
