springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    default-model-expand-depth: -1
  api-docs:
    path: /api-docs
    enabled: true

graphql:
  tools:
    schema-location-pattern: classpath:graphql/**/*.graphqls
  servlet:
    mapping: /chat/graphql

spring:
  jmx:
    enabled: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    virtual-host: /

  cloud:
    config:
      enabled: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI:https://keycloak.onix-dev.ru/realms}/${KC_REALM:spring-app-realm}
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID:spring-app-client}
            client-secret: ${KC_CLIENT_SECRET:clientSecret}
            authorization-grant-type: ${KC_AUTHORIZATION_GRANT_TYPE:client_credentials}

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:0.0.0.0}:${POSTGRES_PORT:5433}/${POSTGRES_DB:chat-service-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_secret}

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    schemas: public
    locations: classpath:db/migration/dev
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_secret}
    url: jdbc:postgresql://${POSTGRES_HOST:0.0.0.0}:${POSTGRES_PORT:5433}/${POSTGRES_DB:chat-service-db}

  cache:
    type: redis

  data:
    redis:
      port: ${REDIS_PORT:5665}
      host: ${REDIS_HOST:localhost}

  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true
    date-format: yyyy-MM-dd'T'HH:mm:ss
    property-naming-strategy: SNAKE_CASE

logging:
  level:
#    root: DEBUG
    jakarta:
      httpclient: DEBUG
    org:
      flywaydb: DEBUG
      keycloak: DEBUG
    web: debug
