management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: account-service
          uri: http://user-api:8080
          predicates:
            - Path=/account/**
          filters:
            - TokenRelay
        - id: box-service
          uri: http://box-api:8080
          predicates:
            - Path=/box/**
          filters:
            - TokenRelay
        - id: flat-service
          uri: http://flat-api:8080
          predicates:
            - Path=/flat/**
          filters:
            - TokenRelay

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI}/${KC_REALM}
            jwk-set-uri: ${KC_ISSUER_URI}/${KC_REALM}/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            authorization-grant-type: ${KC_AUTHORIZATION_GRANT_TYPE}

  jackson:
    deserialization:
      fail-on-ignored-properties: false
    serialization:
      indent-output: false
      write-dates-as-timestamps: false
      write-bigdecimal-as-plain: true
    date-format: yyyy-MM-dd'T'HH:mm:ss
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    jakarta:
      httpclient: DEBUG
    org:
      flywaydb: DEBUG
      keycloak: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    web: debug
