services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    env_file:
      - ${CONFIG_BASE_PATH}/service/minio/minio.env
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - service_fss

volumes:
  minio_data:
    driver: local

networks:
  service_fss:
    external: true
