services:
  gateway:
    image: gateway:latest
    container_name: gateway
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: on-failure
    env_file:
      # component related env
#      - ${CONFIG_BASE_PATH}/api/gateway/someshit.env
      # service related env
      - ${CONFIG_BASE_PATH}/service/postgres/postgres.env
      - ${CONFIG_BASE_PATH}/service/keycloak/realm.env
      - ${CONFIG_BASE_PATH}/service/keycloak/secret/client.env
    ports:
      - "0.0.0.0:8445:8080"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      start_period: 15s
      retries: 5
    networks:
      - gateway_network
      - service_keycloak_network

volumes:
  postgres_data:

networks:
  gateway_network:
    external: true
  api_user_network:
    external: true
  api_box_network:
    external: true
  api_flat_network:
    external: true
  service_keycloak_network:
    external: true
